services:
  db_storage:
    image: postgres:14.3-alpine
    container_name: db_storage
    ports:
      - "5432:5432"
    env_file:
      - .example.env
  
  app_storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_storage
    ports:
      - "8000:8000"
    depends_on:
      - db_storage