"""empty message

Revision ID: 498f1e5ea1bf
Revises: 6553a3ebbbe2
Create Date: 2024-10-01 22:32:47.511933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "498f1e5ea1bf"
down_revision: Union[str, None] = "6553a3ebbbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
